destination: ./_site
auto:        false
lsi:         true
server_port: 4000
pygments:    true
markdown:    maruku
permalink:   pretty

# From blog.solutious.com:
#destination: ./_site
#auto:        false
#lsi:         true
#server_port: 4000
#pygments:    true
#markdown:    maruku
##markdown: rdiscount
#permalink:   pretty